name: dgg-services
services:
  dgg-services-logger:
    build:
      context: ./dgg-services
      dockerfile: ./Dockerfile
    container_name: dgg-services-logger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dgg-services/config:/dgg-services/config
    restart: unless-stopped
  dgg-logger:
    build:
      context: ./dgg-logger
      dockerfile: ./Dockerfile
    container_name: dgg-logger
    volumes:
      - ./dgg-logger/logs:/dgg-logger/logs
      - /home/orangepi/.config/gcloud/application_default_credentials.json:/dgg-logger/credentials/application_default_credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/dgg-logger/credentials/application_default_credentials.json
    restart: unless-stopped
  dgg-relay:
    build:
      context: ./dgg-relay
      dockerfile: ./Dockerfile
    container_name: dgg-relay
    volumes:
      - ./dgg-relay/config:/dgg-relay/config
    restart: unless-stopped
  dggpt:
    build:
      context: ./dggpt
      dockerfile: ./Dockerfile
    container_name: dggpt
    volumes:
      - ./dggpt/config:/dggpt/config
    restart: unless-stopped
  dgg-emotes-bot:
    build:
      context: ./dgg-emotes-bot
      dockerfile: ./Dockerfile
    container_name: dgg-emotes-bot
    volumes:
      - ./dgg-emotes-bot/config:/dgg-emotes-bot/config
    restart: unless-stopped